version: 2.1
orbs:
  ghostinspector: ghostinspector/test-runner@1.0.0
jobs:
  execute-demo-test:
    executor: ghostinspector/default
    steps:
      - ghostinspector/execute-test:
          id: 5c59b4b3d2263522933cad59
          wait: true
workflows:
  test:
    jobs:
      - execute-demo-test
